# Generated by Django 3.0.5 on 2020-05-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_content_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
