# Generated by Django 3.0.5 on 2020-05-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_content_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='ip',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
